### ISSUE TITLE
Add basher config file

### ISSUE THREAD

**Issue by Dauliac** [npryce/adr-tools#113]
[Basher](https://github.com/basherpm/basher) is shell package manager.

That might be a good idea to be compliant with it.

It's only require a sh config file `package.sh` like that:
```bash
BINS=src/adr-config:src/adr:src/adr-generate:src/adr-help:src/adr-init:src/adr-link:src/adr-new:src/adr-upgrade-repository
BASH_COMPLETIONS=autocomplete/adr
ZSH_COMPLETIONS=completions/_package
```

## TODO:
- [ ] Add package.sh manually maintained.
- [ ] Fix `_` prefixed script file to use path of script and not the path of the simlink: 
```bash
declare -xr CURRENT_PATH
CURRENT_PATH=$(dirname "${BASH_SOURCE[0]}")
```
- [ ] Maybe add script to generate it from sources.

**Comment by fayez2021** [comment]
Lol
